version: 2

models:
  - name: stg_customer_snapshot_base
    description: >
      a base table
    columns:
      - name: id
        description: Primary key of the table
        tests:
          - not_null
      - name: first_name
        meta:
          sensitive: true
      - name: last_name
        meta:
          sensitive: true