version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
  - name: stg_customer
    columns:
      - name: id
        tests:
          - unique
          - not_null
